export ADDRESS_DB_ADAPTER=postgresql
export ADDRESS_DB_HOST=lucky.db.elephantsql.com
export ADDRESS_DB_USERNAME=licqovia
export ADDRESS_DB_PASSWORD=DTrUf79U0m29lSoAzLYiM-6mWYxd0Iw0
export ADDRESS_DB_DATABASE=licqovia

export REDIS_HOST=licqovia
export REDIS_PORT=6379